spring.application.name=peopledesk
server.port=8080

#mysql database configurations
#data source url
spring.datasource.url=jdbc:mysql://localhost:3306/peopledesk
spring.datasource.username=root
spring.datasource.password=8355068389@

#jpa configurations
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


